[package]
name = "spellcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
fasthash = "0.4.0"
hex = "0.4.3"
ring = "0.17.8"
